name: Build
on: [push, pull_request]

jobs:
  build:
    strategy: 
      matrix:
        java: [21]
        os: [ubuntu-latest]
    runs-on:  ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup jdk ${{ matrix.java }}
        uses: action/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradlew executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew downloadTranslations build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
